# resetar dados do tópico route.new-position
POST route.new-position/_delete_by_query?conflicts=proceed
{
  "query": {
    "match_all": {}
  }
}
###
# resetar dados do tópico route.new-direction
POST route.new-direction/_delete_by_query?conflicts=proceed
{
  "query": {
    "match_all": {}
  }
}
###
# Criar indice route.new-position
PUT route.new-position
{
  "mappings": {
    "properties": {
      "clientId": {
        "type": "text",
        "fields": {
          "keyword": {
            "type": "keyword"
          }
        }
      },
      "routeId": {
        "type": "text",
        "fields": {
          "keyword": {
            "type": "keyword"
          }
        }
      },
       "timestamp": {
        "type": "date"
      },
      "finished": {
        "type": "boolean"
      },
      "position": {
        "type": "geo_point"
      }
    }
  }
}
###
# Criar indice route.new-direction
PUT route.new-direction
{
  "mappings": {
    "properties": {
      "clientId": {
        "type": "text",
        "fields": {
          "keyword": {
            "type": "keyword"
          }
        }
      },
      "routeId": {
        "type": "text",
        "fields": {
          "keyword": {
            "type": "keyword"
          }
        }
      },
       "timestamp": {
        "type": "date"
      }
    }
  }
}
